---
- name: Set the timezone
  timezone:
    name: Australia/Darwin

- name: Enable privilleged ports
  copy:
    src: files/sysctl/25-privilegedports.conf
    dest: /etc/sysctl.d/25-privilegedports.conf

- name: Delete install-python service unit file
  file:
    path: /etc/systemd/system/install-python.service
    state: absent

- name: Configure automatic ssh 
  block:
    - name: Create skel .ssh dir
      file:
        state: directory
        path: /etc/skel/.ssh/authorized_keys.d
    - name: Copy existing ssh config to skel
      copy:
        src: /var/home/megacorp/.ssh/authorized_keys.d/ignition
        dest: /etc/skel/.ssh/authorized_keys.d
        remote_src: true

- name: Install simple software without any additional configuration
  community.general.rpm_ostree_pkg:
    name: 
      - podman-compose
      - htop
      - tldr
      - g++
      - pass
    state: present
  notify:
  - Reboot if required

- name: Install kubernetes requirements
  block:
    - name: Install requirements for masters
      community.general.rpm_ostree_pkg:
        name: 
          - kubelet
          - kubeadm
          - crio
        state: present
    - name: Copy over kubernetes kernel config
      copy:
        src: files/sysctl/15-kubernetes.conf
        dest: /etc/sysctl.d/10-kubernetes.conf
      when: KUBE_MASTER
      register: kube

- name: Install virtualization packages
  community.general.rpm_ostree_pkg:
    name: 
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-install
    state: present
  when: INSTALL_VIRTUALIZATION
  notify:
  - Reboot if required

- name: Replace NetworkManager with systemd-networkd
  block:
    - name: Install systemd-networkd
      community.general.rpm_ostree_pkg:
        name: systemd-networkd
        state: present
      register: layersAdded

    - name: Reboot if required
      reboot:
      when: layersAdded.changed

    - name: Stop and disable NetworkManager
      systemd:
        name: NetworkManager
        state: stopped
        enabled: false

    - name: Start and enable systemd-networkd
      systemd:
        name: systemd-networkd
        state: started
        enabled: true
  when: INSTALL_SYSTEMD_NETWORKD

- name: Install and configure zsh shell
  block:
    - name: Install zsh
      community.general.rpm_ostree_pkg:
        name: zsh
        state: present
      notify:
      - Reboot if required
    - name: Make ohmyzsh git directory safe
      command: git config --global --add safe.directory /etc/skel/.oh-my-zsh
      check_mode: no
    - name: Clone ohmyzsh repo
      git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: /etc/skel/.oh-my-zsh
    - name: Copy zsh config to skel dir
      copy:
        src: files/zshrc/.zshrc
        dest: /etc/skel
    - name: Copy bash_profile to skel dir
      copy:
        src: files/zshrc/.bash_profile
        dest: /etc/skel
  when: INSTALL_ZSH

- name: Install and configure tmux
  block:
    - name: Install tmux
      community.general.rpm_ostree_pkg:
        name: tmux
        state: present
    - name: Make tmux git directory safe
      command: git config --global --add safe.directory /etc/skel/.tmux
      check_mode: no
    - name: Download pretty tmux from git
      git:
        repo: "https://github.com/gpakosz/.tmux.git"
        dest: /etc/skel/.tmux
    - name: Copy local tmux config to home dir
      command: cp .tmux/.tmux.conf.local .
      args:
        chdir: /etc/skel
    - name: Create tmux config symlink
      command: ln -s -f .tmux/.tmux.conf
      args:
        chdir: /etc/skel
  when: INSTALL_TMUX

- name: Install and configure nvim
  block:
    - name: Install nvim and ripgrep
      community.general.rpm_ostree_pkg:
        name: 
          - neovim
          - ripgrep
        state: present
    - name: Create .config dir in skel
      file:
        path: /etc/skel/.config
        state: directory
    - name: Make nvim git directory safe
      command: git config --global --add safe.directory /etc/skel/.config/nvim
      check_mode: no
    - name: Download nvchad from git
      git:
        repo: https://github.com/nvchad/nvchad
        depth: 1
        dest: /etc/skel/.config/nvim
    - name: Create fonts directory 
      file:
        path: /etc/skel/.local/share/fonts
        state: directory
#    - name: Download font 
#      unarchive:
#        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Terminus.zip
#        dest: /etc/skel/.local/share/fonts
#        remote_src: true
  when: INSTALL_VIM

- name: Configure MOTD
  block:
    - name: Install neofetch
      community.general.rpm_ostree_pkg:
        name: neofetch
        state: present
    - name: Ensure .config file exists
      file:
        path: /etc/skel/.config/neofetch
        state: directory
    - name: Copy neofetch config
      copy:
        src: files/neofetch/config.conf
        dest: /etc/skel/.config/neofetch/
    - name: Copy megacorplogo
      copy:
        src: files/neofetch/megacorplogo
        dest: /etc/skel/.config/neofetch/
