---
- name: Install simple software without any additional configuration
  community.general.rpm_ostree_pkg:
    name: 
      - podman-compose
      - htop
      - tldr
      - gcc
    state: present

- name: Install virtualization packages
  community.general.rpm_ostree_pkg:
    name: 
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-install
      - virt-manager
      - virt-viewer
    state: present
  when: INSTALL_VIRTUALIZATION

- name: Install and configure zsh shell
  block:
    - name: Install zsh
      community.general.rpm_ostree_pkg:
        name: zsh
        state: present
    - name: Make ohmyzsh git directory safe
      command: git config --global --add safe.directory /etc/skel/.oh-my-zsh
      check_mode: no
    - name: Clone ohmyzsh repo
      git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: /etc/skel/.oh-my-zsh
      loop: "{{ USERS }}"
    - name: Copy zsh config to skel dir
      copy:
        src: files/zshrc/.zshrc
        dest: /etc/skel
  when: INSTALL_ZSH

- name: Install and configure tmux
  block:
    - name: Install tmux
      community.general.rpm_ostree_pkg:
        name: tmux
        state: present
    - name: Make tmux git directory safe
      command: git config --global --add safe.directory /etc/skel/.tmux
      check_mode: no
    - name: Download pretty tmux from git
      git:
        repo: "https://github.com/gpakosz/.tmux.git"
        dest: /etc/skel/.tmux
    - name: Copy local tmux config to home dir
      command: cp .tmux/.tmux.conf.local .
      args:
        chdir: /etc/skel
    - name: Create tmux config symlink
      command: ln -s -f .tmux/.tmux.conf
      args:
        chdir: /etc/skel
  when: INSTALL_TMUX

- name: Install and configure nvim
  block:
    - name: Install nvim and ripgrep
      community.general.rpm_ostree_pkg:
        name: 
          - neovim
          - ripgrep
        state: present
    - name: Make nvim git directory safe
      command: git config --global --add safe.directory /var/home/{{ item }}/.config/nvim
      check_mode: no
      loop: "{{ USERS }}"
    - name: Download nvchad from git
      git:
        repo: https://github.com/nvchad/nvchad
        depth: 1
        dest: /var/home/{{ item }}/.config/nvim
      loop: "{{ USERS }}"
    - name: Fix permissions on nvim dir
      file:
        path: /var/home/{{ item }}/.config
        recurse: true
        owner: "{{ item }}"
        group: "{{ item }}"
      loop: "{{ USERS }}"
    - name: Create fonts directory if it doesn't exist
      file:
        path: /var/home/{{ item }}/.local/share/fonts
        state: directory
      loop: "{{ USERS }}"
    - name: Downloaded Terminus font from github
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Terminus.zip
        dest: /var/home/{{ item }}/.local/share/fonts
        remote_src: true
      loop: "{{ USERS }}"
  when: INSTALL_VIM

- name: Configure MOTD
  block:
    - name: Install neofetch
      community.general.rpm_ostree_pkg:
        name: neofetch
        state: present
    - name: Ensure .config file exists
      file:
        path: /var/home/{{ item }}/.config/neofetch
        state: directory
      loop: "{{ USERS }}"
    - name: Copy neofetch config
      copy:
        src: files/neofetch/config.conf
        dest: /var/home/{{ item }}/.config/neofetch/
      loop: "{{ USERS }}"
    - name: Copy megacorplogo
      copy:
        src: files/neofetch/megacorplogo
        dest: /var/home/{{ item }}/.config/neofetch/
      loop: "{{ USERS }}"
    - name: Fix permissions on .config dir
      file:
        path: /var/home/{{ item }}/.config/neofetch
        recurse: true
        owner: "{{ item }}"
        group: "{{ item }}"
      loop: "{{ USERS }}"

