---
- name: Apply base config
  import_tasks: base-config.yml

- name: Kubernize node to be a master
  import_tasks: kube-master.yml
  when: kube_master | default(false)

- name: Apply customizations
  import_tasks: install-preferences.yml
  when: apply_customizations | default(false)
